### ISSUE TITLE
Doesn't work in Firefox

### ISSUE THREAD

**Issue by stevenfabre** [bendc/animate#4]
Would be nice to make it work in Firefox.
The transition property doesn't get added to the element in Firefox.

**Comment by bendc** [comment]
It's supposed to work on Firefox. Do you have an example for me to look at?

**Comment by stevenfabre** [comment]
On Firefox 32.0 on Mac, any animation coming from animate.js isn't working. I tried it with a simple example on my local machine and also on: http://playground.deaxon.com/js/animate/ or http://stripe.com/bitcoin

Hope that helps.

![bug-animate-firefox](https://cloud.githubusercontent.com/assets/2289736/7698954/af7d6c70-fe57-11e4-9d1b-418a1cb75a3d.gif)

**Comment by bendc** [comment]
Firefox 32 is a very old version that I haven't tested. Everything is working fine for me with newer versions though.

**Comment by stevenfabre** [comment]
Fair enough, I assume most Firefox users are pretty tech-savvy and would have an up-to-date version anyway. I thought it was worth sharing ;)
