### ISSUE TITLE
JSHint errors + others

### ISSUE THREAD

**Issue by Bondifrench** [bendc/animate#6]
I was trying `animate.js` as a minimal replacement to jQuery.animate or Velocity, but I encountered a few errors thrown by JSHint on Jsbin: see http://jsbin.com/zeseji/1/edit?html,js,output
I am just trying to replicate [this demo](http://lhorie.github.io/mithril-blog/velocity-animations-in-mithril.html)
Aside from the `Expected an assignment or function call and instead saw an expression` errors, there is a markable difference with when using Velocity. When using `animate.js`, only 2 people are being displayed, not 3 like with Velocity.
Is that a bug? Any ideas what's going on?

**Comment by bendc** [comment]
Just quickly checked and it seems unrelated to the library (looks like you're just trying to use `animate` before importing the actual library). Closing but let me know if you need further information.

**Comment by Bondifrench** [comment]
The library is actually there: if you scroll down the javascript part I pasted the minified version of your code.
Silly me, should have pasted it before the rest of the JS code. My bad.
